### PR TITLE
Plugin Obsidian Release Candidate

### LINKED ISSUE #13: Set Obsidian folder path to map to content folder
I had an existing Obsidian vault that I wanted to align to the quartz configuration, but I'm running into an issue where my Obsidian Vault path doesn't have a variable available. I have a working copy to share -- PR to follow if you're interested.

### LINKED ISSUE #15: Deleting files does not work & publication center shows all files under 'Deleted Notes'
These are two symptoms of the same problem I think.

Every time I open up the publication center, all the notes in the vault are listed under "deleted notes"

Obsidian_TNLxKFvlFy

Additionally, when I select a note which was actually deleted and press "publish selected," the deletion is not passed along to quartz.

I discovered this when trying to move a file and I ended up with duplicates

### LINKED ISSUE #28: Resizing an image currently bugged.
Resizing an image like so:

`![[Image.png|500]]`

Does not work. Inspecting the page shows the following:

``

### LINKED ISSUE #30: Prepare for submission to Obsidian Plugin registry
## Plugin requirements

https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins

- [ ] Remove `fundingUrl` or set up funding.
- [ ] Set proper `minAppVersion` (probably latest.)
- [ ] Add short and accurate description.
- [ ] Check usage of Node API and Electron. These are desktop-only and should be marked as such or changed.
- [ ] Ensure plugin ID is **NOT** included in command ID.
- [ ] Remove sample code.

## Plugin guidelines

https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines

- [ ] Check guidelines compliance.

## Developer policies

https://docs.obsidian.md/Developer+policies

- [ ] Check disclosures.
- [ ] Check licenses.
  - [ ] Check Quartz Themes licenses. (Can probably reasonably assume that themes included in Obsidian's theme browser are fair game. Verify for removed themes.)

## Additional functionality

None at the moment

## Known issues to fix

- [ ] #36 
- [ ] #28 

## Miscellaneous

- [ ] Update README.
- [x] Documentation website.
  - [x] Deploy using Quartz.
- [ ] Preview image for GitHub.
- [x] New logo
  - [x] Quartz logo with up and down arrow(?)
  - [x] Include small lucide-like svg for use in sidebar. (Probably the Quartz icon or something similar/more simplified.)
- [ ] Contributing guidelines.
  - [ ] Issue/PR templates.
- [x] [GitHub Action for Tagged releases](https://docs.obsidian.md/Plugins/Releasing/Release+your+plugin+with+GitHub+Actions).

### LINKED ISSUE #32: Logo
Add a logo to Quartz Syncer.

Add a lucide style svg as well to replace the heart book.

### LINKED ISSUE #33: Documentation with Quartz
Create documentation for Quartz Syncer. Use Quartz. Dogfooding good.

### LINKED ISSUE #36: Other filetypes are not synced
It seems that other filetypes then pictures are not published? In my case I have embedded pdf files which are stored in a folder of my vault which are not published.

### PR DESCRIPTION
**Pull request by saberzero1**
Closes #30 
Closes #15
Closes #33
Closes #32
Closes #28
Closes #36
Closes #13

### CODE REVIEW

File: src/repositoryConnection/QuartzSyncerSiteManager.ts [hunk 1]
```diff
@@ -128,7 +131,7 @@ export default class QuartzSyncerSiteManager {
 				typeof x.path === "string" &&
 				x.path.startsWith(this.settings.contentFolder) &&
 				x.type === "blob" &&
-				x.path !== `${this.settings.contentFolder}/notes.json`,
+				x.path.endsWith(".md"),
```
Comment (saberzero1) [inline src/repositoryConnection/QuartzSyncerSiteManager.ts:134]: Remindme
